### ISSUE TITLE
onGroupChatAgentListUpdate returns can_voice_chat == false isModerator == false for everyone

### ISSUE THREAD

**Issue by hintswen** [CasperTech/node-metaverse#16]
From the looks it it lib\classes\EventQueueClient.ts line 320-327 should be this:
```node
if (updObj['info']['can_voice_chat'] === true)
{
	gcsale.canVoiceChat = true;
}
if (updObj['info']['is_moderator'] === true)
{
	gcsale.isModerator = true;
}
```
However I have checked the value of `event['body']` and it shows `can_voice_chat: true, is_moderator: true` for every agent.

**Comment by Lokomojo** [comment]
This was a bug in LL's javascript LLSD library - fixed it (in our npm fork) and updated the ref.
