### ISSUE TITLE
Group session not restarting after a timeout

### ISSUE THREAD

**Issue by hintswen** [CasperTech/node-metaverse#17]
My bot was in a group which had nothing posted for over 24 hours, I then sent a message to the group and the bot did not see it or even rejoin the group chat. It stayed in all other group sessions and they all had multiple messages posted during this time.

**Comment by DaxDupont** [comment]
Corrade had an issue with this too and I recall even regular users having this issue. Maybe something SL related?

**Comment by Lokomojo** [comment]
I've been using node-metaverse now for over a year as a discord-group chat relay, and I haven't encountered this issue.  I'm going to close it.
