### ISSUE TITLE
Payment-related features

### ISSUE THREAD

**Issue by Welcius** [CasperTech/node-metaverse#25]
Hello! First and foremost, I have to say that I love your project! That being said, I'd like to propose some interesting features that would make the project more complete:

- [x] Send a payment to an specific UUID with a new `bot.clientCommands.grid.sendPayment` method.
- [x] Subscribe to incoming payments with a new `bot.clientEvents.onPaymentReceived.subscribe` method.
- [x] Check your balance using a new `bot.clientCommands.grid.checkBalance` method.
- [ ] Add the field `joinPrice` to GroupInviteEvent that indicates the amount of cash required to join the group.

Ideally the sendPayment method would be promise-based to check if the payment was sent properly, or perhaps a new method `bot.clientEvents.onPaymentCompleted` method to check for that would be better?

Thanks for your work!

**Comment by Lokomojo** [comment]
All implemented - I won't do the "joinPrice" because this is just part of the group invite message string, and the format could change at any time, so it's rather out of scope of this library. If you want to parse this in your application feel free :)

**Comment by Welcius** [comment]
Thank you! This is really helpful :D
