### ISSUE TITLE
Add onMove event

### ISSUE THREAD

**Issue by Tina-King** [CasperTech/node-metaverse#28]
It would be great if we could subscribe to a notification which is fired when the bot moves at least 1 meter in any direction.

Currently there is no way to get the bots position within a region, the event should give the following:

```javascript
        "currentLocation": {
            "regionName": "Passendale",
            "x": 128,
            "y": 17,
            "z": 2074
        }
```

**Comment by Lokomojo** [comment]
Addressed in #31 - just subscribe to your own avatar
