### ISSUE TITLE
Ability to get a list of all avatars in region

### ISSUE THREAD

**Issue by Tina-King** [CasperTech/node-metaverse#31]
It would be great to get a list of all avatars in a region.

Would also be good to add an event for a new avatar entering a region.

The output should be simply be an object containing each avatars data as followed:

```javascript
{
        "agentID": "c1c32889-0b09-4bce-8219-95f38e605198",
        "firstName": "somefirstname",
        "lastName": "somelastname",
        "position": {
            "x": 68,
            "y": 17,
            "z": 43
        }
}
```

**Comment by Lokomojo** [comment]
Added with example
