### ISSUE TITLE
Sometimes group sessions get ignored

### ISSUE THREAD

**Issue by DaxDupont** [CasperTech/node-metaverse#4]
Sometimes group chat does not get passed to the bot until the bot sends a message first.
It's like it's not in the session or something.

**Comment by Lokomojo** [comment]
This actually happens with the regular SL client sometimes too :/

**Comment by Lokomojo** [comment]
I've made a new change in b7e71e11 which may help with this. But I believe this to be an issue with SL itself, since the same behaviour can be witnessed occasionally in Firestorm too.

**Comment by hintswen** [comment]
Looks like this is still happening. My bot was in a group which had nothing posted for over 24 hours, I then sent a message to the group and the bot did not see it or even rejoin the group chat.
