### ISSUE TITLE
Random Generation of MAC Address causes SL to Spam Email Notifications in some cases

### ISSUE THREAD

**Issue by ghost** [CasperTech/node-metaverse#55]
Linden Lab has added in a email notification, whenever you login to SL from what it believes to be a new machine, it bases this seemingly off the MAC Address reported by the client. ( [See here](https://gyazo.com/7617d459880afebea70181f4e63a8ef4))

As Node-metaverse randomly generates one each time it starts, it can cause a lot of email spam notifications. 

A Couple Potential Solutions are as follows, I could probably implement it in a pull request if anyone else thinks it's worth doing. 

1. Have it pull the MAC Address of the first network interface from the OS Module and use that. 
2. Have a login parameter that you can specify either a specific network interface you wish to use, defaulting to a random one if not defined in Parameters.

**Comment by ghost** [comment]
Theoretical  Skeleton Written of it. 
```js
import { networkInterfaces } from 'os';

/// Assuming this code goes in LoginHandler.ts, it'll have the other functions being called. 
function prepareMAC(string inter){ // Inter defaults to either random or the first public interface.

    const interfaces = networkInterfaces();

    // if interface is set to be random, generate a random MAC and Return. 
    if(interface == "random"){
    return LoginHandler.GenerateMAC();
    }
    else{
      // Iterate through the network interface object until you find a interface matching the name of interface, or if it is undefined, stop at the first one that has internal set to false. 
    }
    
}
```

**Comment by Lokomojo** [comment]
I'll change this to generate an ID based on account name. I don't like hidden data leakage.

**Comment by ghost** [comment]
Sounds good, so perhaps a hash of it?
