### ISSUE TITLE
setGeometry does not rotate avatar

### ISSUE THREAD

**Issue by sociallydead-net** [CasperTech/node-metaverse#58]
I am trying to rotate my but with avatar.setGeometry but what ever I set as rotation there is no movement at all. 

another question I have, is there any event that fires when really all of the bot is initiaized? when agent for example can no longer return undefinded and all is save to use ?

**Comment by Lokomojo** [comment]
Thanks to @gwigz this is resolved now

**Comment by gwigz** [comment]
@TomMettam looks like they're read-only since the 0.8 refactor, don't see a method to change them?
